### ISSUE TITLE
Settings Panel

### ISSUE THREAD

**Issue by shambler123** [jlucidar/fpv_viewer_android#28]
Create a Settings Panel to manage:
- DVR Settings ( File Location, Auto Record , ...)
- Telemetrie Settings (For late e. g. Crossfire telemetry)
- About
- Version 
- License

**Comment by shambler123** [comment]
@all just added the basics.

**Comment by fichek** [comment]
* A toggle switch to hide/show the #18 watermark (maybe a slider to make it more/less transparent? too much?)
* Important links (fpvout.com, discord, github, opencollective...)

**Comment by jlucidar** [comment]
The watermark being toggled on main screen click isn't enough ? I don't think adding a settings for this would be necessary.

**Comment by fichek** [comment]
> The watermark being toggled on main screen click isn't enough ? I don't think adding a settings for this would be necessary.

There seem to be a few users who are very opinionated about this 🙂 I'd say tap to show/hide was fine for now, but when we add more UI like the record button, I'd personally want all that UI to hide and the overlay to always stay, so some customization would be nice either way.

**Comment by jlucidar** [comment]
yeah, let's keep the list as short as posssible for the moment. Let's see what people think when they have beta in hands and we'll move from there :)

**Comment by squshy7** [comment]
One really important item id like to see in the root of the settings menu, and preferably not buried, is a redirect to the web app. This will ensure maximum compatibility in case the user is having an issue with the native app, and goes along with the "any screen, any time" theme. I would ALSO link to the web app in any sort of "having issues?" FAQ type menu we put in there.

If we like this idea, I'll point out that since some users use a different default browser, this might need to pop up in the auto-temporary-chrome-page thing that android does. Or, live.fpvout.com could implement a browser check but that's beyond the scope of this

**Comment by jlucidar** [comment]
This have been merged in dev :) Thanks to everyone !
